package com.movies.acmeflix.model.MovieModel.enumeration;

public enum Category {
    ACTION,ADVENTURE,DRAMA,COMEDY,SCIENCE_FICTION,THRILLER,HORROR,FANTASY,MUSICAL,MYSTERY,ROMANCE,SPORT,WESTERN,CRIME,ANIMATION,SUPERHERO
}
